config/routes.rb
Rails.application.routes.draw do

  resources :media_items

  resources :users

  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'activate/:code' => 'activations#create', :as => :activate

  get 'signup' => 'users#new', :as => :signup

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions, except: [:destroy]

  root 'users#index'

end

app/models/media_item.rb
# == Schema Information
#
# Table name: media_items
#
#  id         :integer          not null, primary key
#  name       :string
#  type       :string
#  user_id    :integer
#  link       :string
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# Model MediaItem defines the basic class for the collecions
#
class MediaItem < ActiveRecord::Base

  belongs_to :user

  validates :name, presence: true, uniqueness: {scope: :user_id}
  validates_inclusion_of :type, in: %w[LinkItem PhotoItem VideoItem]

  scope :ordered, -> { order(:name) }

end

app/controllers/media_items_controller.rb
# This is the main controller to process model MediaItem
#
class MediaItemsController < ApplicationController

  # before_action :set_media_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /media_items
  # GET /media_items.json
  def index
    # @media_items = MediaItem.all
    respond_to do |format|
      format.html do
        @grid = initialize_grid @media_items
      end
      format.json do
        @media_items = @media_items.page(params[:page]) if params[:page].present?
        @media_items = @media_items.per(params[:per_page]) if params[:per_page].present?
      end
    end
  end

  # GET /media_items/1
  # GET /media_items/1.json
  def show
  end

  # GET /media_items/new
  def new
    # @media_item = MediaItem.new
  end

  # GET /media_items/1/edit
  def edit
  end

  # POST /media_items
  # POST /media_items.json
  def create
    # @media_item = MediaItem.new(media_item_params)

    respond_to do |format|
      if @media_item.save
        format.html { redirect_to media_item_path(@media_item), notice: t('media_items.was_created') }
        format.json { render :show, status: :created, location: @media_item }
      else
        format.html { render :new }
        format.json { render json: @media_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_items/1
  # PATCH/PUT /media_items/1.json
  def update
    respond_to do |format|
      if @media_item.update(media_item_params)
        format.html { redirect_to media_item_path(@media_item), notice: t('media_items.was_updated') }
        format.json { render :show, status: :ok, location: @media_item }
      else
        format.html { render :edit }
        format.json { render json: @media_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_items/1
  # DELETE /media_items/1.json
  def destroy
    @media_item.destroy
    respond_to do |format|
      format.html { redirect_to media_items_url, notice: t('media_items.was_deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_media_item
  #   @media_item = MediaItem.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def media_item_params
    list = [
      :name, :type, :user_id, :link, :image
    ]
    params.require(:media_item).permit(*list)
  end
end

app/views/media_items/_form.html.haml
= simple_form_for(@media_item) do |f|
  = f.error_notification

  .form-inputs
    - if @media_item.new_record?
      = f.input :type
    = f.input :name
    = f.association :user
    = f.input :link
    = f.input :image

  .form-actions
    = f.button :submit

app/views/media_items/edit.html.haml
- title t('.title')

%p.nav
  - if can? :index, MediaItem
    = link_to t('back'), media_items_path, class: 'index'
  - if can? :show, @media_item
    = link_to t('show'), @media_item, class: 'show'
= render 'form'

app/views/media_items/index.html.haml
- title t('.title')

- if can? :new, MediaItem
  %p.nav= link_to t('.new_media_item'), new_media_item_path, class: 'new'

- if @grid
  = grid @grid do |g|
    - g.column name: MediaItem.human_attribute_name(:name),
      :attribute => 'name' do |media_item|
      - media_item.name
    - g.column name: MediaItem.human_attribute_name(:type),
      :attribute => 'type' do |media_item|
      - media_item.type
    - g.column name: MediaItem.human_attribute_name(:user),
      :attribute => 'user_id' do |media_item|
      - media_item.user.try :name
    -# g.column name: MediaItem.human_attribute_name(:link),
      :attribute => 'link' do |media_item|
      - media_item.link
    -# g.column name: MediaItem.human_attribute_name(:image),
      :attribute => 'image' do |media_item|
      - media_item.image
    - g.column do |media_item|
      - if can? :show, media_item
        - link_to t('show'), media_item_path(media_item), class: 'show'
    - g.column do |media_item|
      - if can? :edit, media_item
        - link_to t('edit'), edit_media_item_path(media_item), class: 'edit'
    - g.column do |media_item|
      - if can? :destroy, media_item
        - link_to t('destroy'), media_item_path(media_item),
          data: {confirm: t('.confirm', default: 'Are you sure?')},
          method: :delete, class: 'destroy'
-else
  %table
    %thead
      %tr
        %th= MediaItem.human_attribute_name :name
        %th= MediaItem.human_attribute_name :type
        %th= MediaItem.human_attribute_name :user
        -# %th= MediaItem.human_attribute_name :link
        -# %th= MediaItem.human_attribute_name :image
        %th{:colspan => 3}= t 'actions'

    %tbody
      - @media_items.each do |media_item|
        %tr{ :class => cycle(:odd, :even) }
          %td= media_item.name
          %td= media_item.type
          %td= media_item.user.try :name
          -# %td= media_item.link
          -# %td= media_item.image
          %td.action
            - if can? :show, media_item
              = link_to t('show'), media_item_path(media_item), class: 'show'
          %td.action
            - if can? :edit, media_item
              = link_to t('edit'), edit_media_item_path(media_item), class: 'edit'
          %td.action
            - if can? :destroy, media_item
              = link_to t('destroy'), media_item_path(media_item),
                data: {confirm: t('.confirm', default: 'Are you sure?')},
                method: :delete, class: 'destroy'

app/views/media_items/new.html.haml
- title t('.title')

- if can? :index, MediaItem
  %p.nav= link_to t('back'), media_items_path, class: 'index'

= render 'form'

app/views/media_items/show.html.haml
- title t('.title')

%p.nav
  - if can? :index, MediaItem
    = link_to t('back'), media_items_path, class: 'index'
  - if can? :edit, @media_item
    = link_to t('edit'), edit_media_item_path(@media_item), class: 'edit'

%dl
  %dt= MediaItem.human_attribute_name :name
  %dd= @media_item.name
  %dt= MediaItem.human_attribute_name :type
  %dd= @media_item.type
  %dt= MediaItem.human_attribute_name :user
  %dd= @media_item.user.try :name
  - if @media_item.is_a? PhotoItem
    %dt= MediaItem.human_attribute_name :image
    %dd= @media_item.image
  - else
    %dt= MediaItem.human_attribute_name :link
    %dd= @media_item.link