config/routes.rb
Rails.application.routes.draw do

  resources :media_items

  resources :users

  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'activate/:code' => 'activations#create', :as => :activate

  get 'signup' => 'users#new', :as => :signup

  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'login' => 'user_sessions#new', :as => :login

  resources :user_sessions, except: [:destroy]

  root 'users#index'

end

app/models/user_session.rb
# Authlogic session for users
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = t 'authlogic.logged_in',
          name: @user_session.record.name
      redirect_to_target_or_default(root_url)
    else
      logger.info "UserSessionsController#create@#{__LINE__} #{@user_session.errors.inspect} invalid"
      ([:login, :password] - @user_session.errors.keys).each do |key|
        mkey = key == :login ? 'login_not_found' : 'password_invalid'
        @user_session.errors[key] = t "authlogic.error_messages.#{mkey}"
      end
      render :action => 'new'
    end
  end

  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = t 'authlogic.lgged_out'
    redirect_to root_url
  end
end

app/views/user_sessions/new.html.haml
- title t('.login')

.other_actions
  %p
    = t('authlogic.do_not_have_account')
    = link_to t('authlogic.sign_up'), signup_path
  %p
    = t('password_resets.forget')
    = link_to t('password_resets.reset_password'), new_password_reset_path

= simple_form_for @user_session do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :password
  .form-actions
    = f.button :submit, t('authlogic.do_login')